### PR TITLE
Operator Release `RELEASE.2024-09-23T16-32-06Z`

### PR DESCRIPTION
**Pull request by pjuarezd**

### CODE REVIEW

**Comment by donatello** [comment]
Release automation requires that first word of the commit message is the release name. Please remove the first word here. Also the time stamp in the release name must be the gir committer time of the previous commit. These checks are there to ensure sanity and make the release automation more reliable.

**Review by dvaldivia — APPROVED** [review]
LGTM

**Comment by donatello** [comment]
Ah ok this is not the problem to release this project

**Comment by pjuarezd** [comment]
> Ah ok this is not the pr to release this project

right, it’s fine, here we are not going to build releases

**Pull request merged**
